params:
  num_image_pairs: 25
  num_matches_per_image_pair: 100

networks:
  caterpillar_3:
    path_to_network_params: trained_models/tutorials/caterpillar_3/003501.pth
  pineapple_3:
    path_to_network_params: trained_models/dexai/pineapple_3/001501.pth
  mango_3:
    path_to_network_params: trained_models/dexai/mango_3/003501.pth
  kale_3:
    path_to_network_params: trained_models/dexai/kale_3/003501.pth
  mango_pieces_3:
    path_to_network_params: trained_models/dexai/mango_pieces_3/014034.pth
  romaine_pieces_3:
    path_to_network_params: trained_models/dexai/romaine_pieces_3/014003.pth

dataset: [] # which dataset to use, not used for now

output_dir: analysis
