mango-hotel:
  hotel:
    path_to_data_directory: '/home/hotel/fullstack/src/log_robot'

paladin-23:
  manuelli:
    path_to_data_directory: '/home/manuelli/data'

paladin-44:
  manuelli:
    path_to_data_directory: '/media/hdd/data'

iiwa-2:
  manuelli:
    path_to_data_directory: '/home/manuelli/data'

wei:
  wei:
    path_to_data_directory: '/home/wei/data'